// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNReaS0Gepq6QrC7UA7_M66r_7HTFIcqg',
    appId: '1:1098757513078:web:3ea96f470dfe65c8f3a457',
    messagingSenderId: '1098757513078',
    projectId: 'paperchase-7ad1d',
    authDomain: 'paperchase-7ad1d.firebaseapp.com',
    storageBucket: 'paperchase-7ad1d.firebasestorage.app',
    measurementId: 'G-9S7JFLMCHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzhSFOFzVuSfo953jOTkMg2z-pAN2o74',
    appId: '1:1098757513078:android:504aff2e25702dd4f3a457',
    messagingSenderId: '1098757513078',
    projectId: 'paperchase-7ad1d',
    storageBucket: 'paperchase-7ad1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp1GY6LaJgtIdRhNDd-9J3XjTKokbejAM',
    appId: '1:1098757513078:ios:a38af1f79b4b6e0df3a457',
    messagingSenderId: '1098757513078',
    projectId: 'paperchase-7ad1d',
    storageBucket: 'paperchase-7ad1d.firebasestorage.app',
    iosClientId: '1098757513078-qqqtc113mmpod90o1jn1thv2rea08rlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperchaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp1GY6LaJgtIdRhNDd-9J3XjTKokbejAM',
    appId: '1:1098757513078:ios:a38af1f79b4b6e0df3a457',
    messagingSenderId: '1098757513078',
    projectId: 'paperchase-7ad1d',
    storageBucket: 'paperchase-7ad1d.firebasestorage.app',
    iosClientId: '1098757513078-qqqtc113mmpod90o1jn1thv2rea08rlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperchaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNReaS0Gepq6QrC7UA7_M66r_7HTFIcqg',
    appId: '1:1098757513078:web:82c9b4405c897bd7f3a457',
    messagingSenderId: '1098757513078',
    projectId: 'paperchase-7ad1d',
    authDomain: 'paperchase-7ad1d.firebaseapp.com',
    storageBucket: 'paperchase-7ad1d.firebasestorage.app',
    measurementId: 'G-W2P18RYHBZ',
  );
}
